service: eriks-lambda # NOTE: update this with your service name

vars:
  stage: ${opt:stage, dev}
  regions:
    stage: eu-north-1
    production: us-east-1


provider:
  profile: experiments
  name: aws
  runtime: python3.7

  stage: ${self.vars.stage}
  region: ${self.vars.regions.${self.vars.stage}}

functions:
  eriks-super-lambda:
    handler: handler.get_body
    events:
      - http:
          path: hello
          method: GET
          authorizer:
            name: my-authorizer
            type: request
            identitySource: method.request.querystring.api_key
  my-authorizer:
    handler: handler.auth
    environment:
      PLUGIN_SECRET: 'very_secret'
