service: eriks-lambda # NOTE: update this with your service name

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: lilja-api.funnel.io
    stage: ${self:provider.stage}
    basePath: ''
    createRoute53Record: true

provider:
  name: aws
  runtime: python3.7

  stage: ${opt:stage, 'stage'}
  region: ${opt:region, 'eu-north-1'}

functions:
  eriks-super-lambda:
    handler: handler.get_body
    events:
      - http:
          path: hello
          method: GET
          authorizer:
            name: my-authorizer
            type: request
            identitySource: method.request.querystring.api_key
  my-authorizer:
    handler: handler.auth
    environment:
      PLUGIN_SECRET: 'very_secret'
